name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup OCaml
      uses: avsm/setup-ocaml@v2
    - name: Install depext module
      run: opam install -y opam-depext
    - name: Pin locally
      run: opam pin -y add --no-action .
    - name: Install locally
      run: opam depext -y -i mlsub
    - name: Build
      run: eval $(opam env) && make
    - name: Test
      run: eval $(opam env) && make test
